import * as fs from 'fs';
import * as path from 'path';
import { execFile as execFileCb } from 'child_process';
import { promisify } from 'util';
import { getConfig } from '@/lib/config';

const execFile = promisify(execFileCb);

export interface INginxService {
  configureProject(slug: string, containerPort: number): Promise<void>;
  removeProject(slug: string): Promise<void>;
}

function generateServerBlock(slug: string, containerPort: number, baseDomain: string): string {
  return `# Auto-generated by DropDeploy — do not edit manually.
# Project: ${slug}  Port: ${containerPort}
server {
    listen 80;
    server_name ${slug}.${baseDomain};

    location / {
        proxy_pass http://127.0.0.1:${containerPort};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }
}
`;
}

export class NginxService implements INginxService {
  constructor(private readonly cfg: typeof getConfig) {}

  async configureProject(slug: string, containerPort: number): Promise<void> {
    const config = this.cfg();

    if (config.NODE_ENV !== 'production') {
      console.warn(
        `[NginxService] Non-production environment — skipping nginx config for ${slug}`
      );
      return;
    }

    const configPath = path.join(config.NGINX_CONFIG_PATH, `dropdeploy-${slug}`);
    const content = generateServerBlock(slug, containerPort, config.BASE_DOMAIN);

    await fs.promises.writeFile(configPath, content, 'utf8');

    try {
      await execFile('nginx', ['-t']);
    } catch (err) {
      // Bad config — remove it and propagate
      await fs.promises.unlink(configPath).catch(() => undefined);
      throw new Error(
        `[NginxService] nginx config test failed for ${slug}: ${(err as Error).message}`
      );
    }

    await execFile('nginx', ['-s', 'reload']);
  }

  async removeProject(slug: string): Promise<void> {
    const config = this.cfg();

    if (config.NODE_ENV !== 'production') {
      console.warn(
        `[NginxService] Non-production environment — skipping nginx removal for ${slug}`
      );
      return;
    }

    const configPath = path.join(config.NGINX_CONFIG_PATH, `dropdeploy-${slug}`);

    try {
      await fs.promises.unlink(configPath);
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code !== 'ENOENT') {
        throw err;
      }
    }

    await execFile('nginx', ['-s', 'reload']);
  }
}

export const nginxService = new NginxService(getConfig);
